opsani/servox

CHANGELOG.md
poetry.lock
pyproject.toml
servo/checks.py
servo/cli.py
servo/connector.py
servo/connectors/kubernetes.py
servo/connectors/prometheus.py
servo/connectors/vegeta.py
servo/servo.py
servo/types.py
servo/utilities/inspect.py
tests/checks_test.py
tests/cli_test.py
tests/connector_test.py
tests/connectors/kubernetes_test.py
tests/utilities/inspect_test.py

This PR contains a revised and expanded implementation of the `servo check` functionality.
For the uninitiated, a `Check` object represents a runtime for that a particular dependency is available or that configuration is correct. Examples include "Can I talk to Redis?", "Does my service account in Kubernetes have sufficient permissions?", and "Are my Prometheus queries well-formed and returning results?".
As I have been building out Opsani Dev and doing a ton of setup and tear-down work, I have become increasingly convinced that checks represent a key driver of deployment efficiency and user experience. The most difficult aspects of getting a deployment live are **gathering information** (a social problem) and **verifying requirements and configuration** (a technical problem). Checks …

Enhanced checks architecture

---

CHANGELOG.md
servo/api.py
servo/assembly.py
servo/checks.py
servo/cli.py
servo/configuration.py
servo/connector.py
servo/connectors/kubernetes.py
servo/logging.py
servo/runner.py
servo/servo.py
servo/utilities/associations.py
servo/utilities/key_paths.py
servo/utilities/pydantic.py
tests/checks_test.py
tests/conftest.py
tests/connector_test.py
tests/servo_test.py
tests/utilities/associations_test.py

This PR introduces a number of enhancements to enable the servo to operate in challenging environments and gracefully handle transient errors. It also introduces a new `servo` configuration stanza for settings that apply to functionality provided by the library to all connectors.
Specific changes include:
* `servo` configuration stanza
* timeouts are now configurable for connect, read, write, and acquiring a connection from the pool
* SSL is now configurable. Verification can be disabled (but please don't do this) and non-validating SSL certificate chains from private PKI can be loaded
* Proxies can be configured for connecting to the Opsani API or any other web service as necessary
* Introduced associated objects API for managing supporting objects that don't need to be exposed as …

Networking enhancements: backoff, retry, proxies, timeouts

---

CHANGELOG.md
servo/cli.py
servo/runner.py

This PR adds two no options to the `servo run` command:
* `--interactive / -i` - Ask for confirmation before proceeding with commands.
* `--no-poll` - Disables the polling command loop after starting the Assembly.

Add --interactive and --no-poll modes for servo run

---

tests/connectors/kubernetes_test.py

- increase timeout config of test_adjust_tuning_insufficient_resources
from 5 seconds to 10

Increase timeout of occasionally failing CI test

---

servo/connectors/kubernetes.py
tests/connectors/kubernetes_test.py

- Add tuning optimization check for restarted containers
- Update scheduling-failed reasons to unschedulable
- Don't treat start-failed as unschedulable
- update event_type == ERROR to use message instead of reason
- Update ReplicaFailure, Progressing.status == False to correct reason
- Move handle_error out of apply timeout error handling to prevent
redundant invokation
- wait for gather awaitable cancellation on timeout to prevent
exception never retrieved warning
- Set correct message, reason on final settlement check, add warning that
handle_error was not run for it
- Refactor tests to provide context on the error if it fails assertions
- Add tests for OOMKilled on adjustment
- Add test for tuning optimization start-failed

Implement correct rejection reasons (Fixes SOL-344, SOL-349)

---

README.md

0.8 is 800 millicores, not 0.8 millicores. It's 0.8 vCPU units.

corrected units in README.md typo

---

servo/connectors/kubernetes.py
tests/helpers.py
tests/kubernetes_test.py
tests/system/autoscaler_test.py
tests/system/conftest.py
tests/system/docker_test.py

- Add check for Vertical Pod Autoscaler
- Add system/integration tests for VPA check success/failure
- Update subprocess helper to pass in kwargs
- Update minikube test fixture to use test kubeconfig
- Update test_run_servo_on_kind to validate against `kubectl logs` output (Fixes ENG-28)

Add onboarding to check for VPA

---

servo/connectors/opsani_dev.py

All metrics are now averages, except explicit "total" metrics
main_pod_average metric is removed
Requires updates to template to ensure matching metric names
dev2.3 rc live-traffic template being updated to match

Update prom metrics to support ENG-51 renaming

---

poetry.lock
pyproject.toml

- Switch from using github hosted kubernetes_asyncio fork to using pypi
repackaged version of fork to allow servox to publish to pypi

Update poetry deps to use kubernetes-asyncio-cr-patch PyPI package

---

servo/connectors/kubernetes.py
servo/connectors/prometheus.py
servo/connectors/vegeta.py
servo/events.py
servo/runner.py
servo/servo.py
servo/types.py
tests/connectors/kubernetes_test.py
tests/fake_test.py
tests/helpers.py
tests/runner_test.py
tests/servo_test.py

(supersedes closed PR#311)
send control=Control(param['control']) when dispatching 'describe'
event, fix all existing handlers of 'describe' to have a matching arg, so they
can accept this change.
call 'before_event' handlers with the same data as on_event, fix all
existing 'before' handlers to accept this; modify handler type checking to 
compare 'before' handlers to the event's defined 'on' handler type, but with return type=None
add 'environment' to the types/Control() class (type =
Optional[dict[str, Any]])

Changes for OKO integration [preparation for ENG-165, ENG-166]

---

servo/connectors/opsani_dev.py

Rename _avg metrics to remove _avg name.

Update prometheus metrics for opsani Dev removing _avg

---

servo/api.py
tests/api_test.py

Changes ServoStatus from generic failed to cancelled (unique from 'aborted' which is utilized in the upcoming fast-fail feature)

daniel/eng-310 EventCancelledError specificity

---

servo/cli.py
servo/connectors/opsani_dev.py
tests/connectors/opsani_dev_test.py

- move default envoy sidecar image tag from cli to opsani_dev connector
- make image a required argument of cli inject-sidecar command
- update opsani_dev configuration to allow setting of sidecar image

Make envoy proxy image name and tag configurable

---

servo/connectors/kubernetes.py

- Replace list.append with list.extend

Fix k8s permissions check error with rollout

---

servo/connectors/kubernetes.py
tests/conftest.py
tests/connectors/kubernetes_test.py
tests/connectors/opsani_dev_test.py
tests/connectors/prometheus_test.py
tests/runner_test.py

- Added CanaryOptimizaton.temporary_tuning_pod context manager to
facilitate test teardown
- Added kubetest_teardown to conftest for tests where namespace is not
created kubetest
- Update argo rollout test fixture to work with fewer permission
- Add xfail for intermittent threading issue test failure
- Drop cluster-admin rolebinding from tests
- Configure namespaces prometheus tests
- Add kubetest_teardown and tuning pod teardown to prometheus related
integration tests

Update servox for new CICD setup

---

servo/connectors/opsani_dev.py

- Add "sum by(kubernetes_pod_name)" to success and error rate metrics so
they are averaged by the number of pods instead of averaged by the
number of pods times the number of "envoy_response_code_class"es

Fix success/error rate metrics

---

poetry.lock
pyproject.toml
servo/connectors/kubernetes.py

- Update pyproject.toml and poetry.lock
- Add k8s connector missing explicit imports, alphabetize
- Update KubernetesModel.api_client context manager with default_headers
argument
- Set default_header content-type = application/merge-patch+json for
rollout patch method

Set kubernetes_asyncio back to official package

---

servo/connectors/kube_metrics.py
servo/connectors/kubernetes.py
servo/connectors/opsani_dev.py
servo/types/__init__.py
servo/types/kubernetes.py
setup.cfg
tests/connectors/opsani_dev_test.py
tests/connectors/prometheus_test.py

- Add types module for kubernetes
- Implement new Pod method get_logs_for_container_statuses
- Add include_container_logs param to raise_for_status methods
- Include container logs in rejection messages for restart counts (
implementation for other failures TBD)
- Introduce container_logs_in_error_status flag to kubernetes config

Add container logs to restart count error messages

---

pyproject.toml

default cannot be set in `Annotated`"

Pin pydantic to 1.8.2 due to issue with "`Field`

---

.github/workflows/release.yml
.github/workflows/test.yaml
Dockerfile
servo/connector.py
setup.cfg
tests/system/cli_test.py

Fix test failures:
- pkg_resources is deprecated. Switch over to importlib for connector loading
- update poetry so urllib3 is pinned as needed to prevent `HTTPResponse' object has no attribute 'strict'` errors
- mark test_generate_opsani_dev xfail due to issue with --dependency arg that I don't have time to debug. Use case is deprecated anyway

Use importlib to load connectors

---

servo/api.py
servo/checks.py
servo/configuration.py
servo/servo.py
tests/connector_test.py
tests/servo_test.py

- Ensure backoff is applied to non-onboarded workloads to reduce noise
on CO
- Disable diagnostics calls to assets API in config defaults
- implement simple exponential backoff for checks to reduce noise in CO
from failing Opsani API Connectivity check

Optserv 606 optserv 608

---

helm/templates/configmap.yaml
servo/api.py
servo/configuration.py
servo/errors.py
servo/logging.py
servo/runner.py
servo/servo.py
tests/servo_test.py

- pass servo_uid from helm values to servo config yaml
- Add servo_uid to backend Request model
- Unify metrics response instantiation with other commands via Status.ok
- Allow setting arbitrary Status properties via from_error()
- Add command_uid to backend param Status model
- Add command_uid to backend CommandResponse model
- Add servo_uid to servo configuration model
- Add new error type for unexpected command uid
- Include command_uid in progress reporting logger sink
- Store command_uid returned by WHATS_NEXT into contextvar
- Send command_uid in command completions/errors
- Handle servo UID mismatch by sleeping for 1 hour wait for deprovision
- Add UnexpectedCommandIdError to progress exception restart handling
- Include servo_uid in startup logging
- Detect and raise …

Optserv 690 implement handling for servo uid and command id into servox

---

servo/logging.py
servo/runner.py

- Add methods to clear progress reporting queue
- Add/set reference property of ServoRunner to parent AssemblyRunner
- Call clear_progress_queue prior to each command completion

Clear progress reporting queue on cmd completion

---

servo/types/settings.py
tests/conftest.py
tests/connectors/kubernetes_test.py
tests/kubernetes_test.py
tests/types/settings_test.py

- custom validator for RangeSetting classes will only be logged instead of raising errors
- Add reusable fixture for capturing log messages
- update unit tests to validate log messages instead of validation error

Convert rangesetting validations to log errors

---

servo/assembly.py
servo/cli.py
servo/connectors/kubernetes.py
servo/connectors/prometheus.py
servo/events.py
servo/runner.py
servo/utilities/subprocess.py
tests/servo_test.py

This update replaces instances of gather() with (default behavior) return_exceptions=false since only the future that raises the exception will be stopped. TaskGroup ensures all taks complete or are cancelled before the with block is exited. This update is also applied to gather()s that are wrapped by task leak handling identical to TaskGroup to reduce the boilerplate added by said handling
This update is not applied to gather invocations that need to return (all) exceptions since that is not supported by TaskGroup. It is also not applied to gathers used as a shorthand for try catch pass logic (except for a case where logging was improved)
NOTE we avoid the use of create_task in generators in favor of list comprehensions which call create_task right away instead of lazily (doesn't matter …

First pass update gather methods to prevent task leaks on error

---

servo/api.py
servo/assembly.py
servo/checks.py
servo/cli.py
servo/connectors/kube_metrics.py
servo/connectors/kubernetes.py
servo/connectors/prometheus.py
servo/errors.py
servo/events.py
servo/logging.py
servo/runner.py
servo/servo.py
tests/conftest.py
tests/connectors/kubernetes_test.py
tests/connectors/opsani_dev_test.py
tests/connectors/prometheus_test.py
tests/fake_test.py
tests/helpers.py
tests/logging_test.py
tests/pubsub_test.py
tests/repeating_test.py
tests/runner_test.py
tests/servo_test.py

- refactor connector initialization to be member method load_connectors of servo instead of procedural assembly logic
- update servo to store connector type routes loaded from config yam/default values
- fix servo attach() and detach() referencing servo module
- refactor servo shutdown to send gootbye event, add reason param to shutdown to include in request
- use TaskGroup for checks rememdy processing to avoid task leaks
- Move AssemblyRunner run() args poll, interactive to class properties set on init
- fix incorrected type hint on _default_context_manager
- Update progress handler to support creating its queue processor task with an external task group tied to lifetime of the AssemblyRunner
- Update progress handler sink to require servo from extra or context and include in progress …

Optserv 1269 part 2 servox async logic hardening
